import Header from '@/components/Header';
import Footer from '@/components/footer';

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-white flex flex-col">
      <Header />
      <main className="flex-1 container-main mx-auto px-4 py-0">
        {/* Banner Header */}
        <div className="w-full bg-[#f9efe3] py-12 mb-10 rounded-b-3xl shadow-md">
          <h1 className="text-4xl md:text-5xl font-extrabold text-gray-900 text-center tracking-tight">Privacy Policy</h1>
          <p className="text-lg md:text-xl text-gray-700 text-center mt-4 max-w-2xl mx-auto opacity-90">Learn how we collect, use, and protect your information at theweddingandevent, a subsidiary of MCT Business Private Ltd.</p>
        </div>
        <div className="prose max-w-4xl mx-auto text-gray-800">
          <p><strong>Privacy Policy | theweddingandevent a subsidiary of MCT Business Private Ltd.</strong></p>
          <p>This privacy policy (“Policy”) explains our policy regarding the collection, use, disclosure and transfer of your information by MCT Business Private Ltd or any of its affiliate(s) (“we” or “us” or “our”), which operates the website (*) ("Site") and App “theweddingandevent” and other services including but not limited to recording credit/payment, communicating dues/balances via the site and application, any mobile or internet connected device or otherwise (collectively the “theweddingandevent”). This Policy forms part and parcel of the Terms of Use for the “theweddingandevent” Website or App (hereinafter collectively referred to as the “ Online Platform”). Capitalized terms that have been used here but are undefined shall have the same meaning as attributed to them in the Terms of Use. Users (as defined hereinafter) are requested to read this Policy in conjunction with the Terms of Use. The Online Platform provides an online booking method whereby various service providers affiliated with the wedding industry of Pakistan can register themselves on the Online Platform who can then be booked by the other users of the Online Platform (collectively, “Services”). Please note that ‘Services’ would include any other future services we may provide or propose to provide. As we update, improve and expand the Online Platform Service, this Policy may change, so please refer back to it periodically. By accessing the Site, App or otherwise using the “theweddingandevent” Services, you consent to the collection, storage, and use of the personal information you provide (including any changes thereto as provided by you) for any of the services that we offer. We respect the privacy of the users of the “theweddingandevent" Services (“Users” or “you”) and are committed to reasonably protect it in all respects. The information about the User as collected by us is: (a) information supplied by Users and (b) information automatically tracked while using a website and mobile device having “theweddingandevent" Services enabled (collectively referred to as “Information”). By using “theweddingandevent" Services, you agree to this Policy. If you do not agree with any term in this Policy, please do not use / avail of the “theweddingandevent" Services.</p>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Information supplied by users</h2>
          <p>To avail certain Services on the Online Platform, Users are required to provide certain personal information for the registration process, which may include: a) their name, b) email address, c) mobile number, d) business entity information, (e) account number of the Users, (f) KYC details and any other such information as required. The Information as supplied by the Users enables us to provide the Services and improve the Online Platform Services and provide you the most user-friendly experience. In some cases/provision of certain service(s) or utility(ies), we may require your contact address and identity details as well. Further, upon downloading the website and App, Users are requested to share access to their contact list (as stored on their mobile device on which the App is downloaded), so as to enable the User to share payment/credit updates with his/her customers (who might be or might not be Users). In an attempt to improve our Services, we may, from time to time, collect any information (other than what is mentioned above) from Users through App / Site. You may be assured that we do not share this data with any third party except in accordance with the terms of this Policy. We may access a user's inventory of installed apps and treat this data as personal or sensitive data subject to this Policy, secure transmission, and prominent disclosure requirements of User. All Information is service dependent, and we may use the Information to provide the Services, maintain, protect, and improve the “theweddingandevent" Services, and for developing new services. We may also use your email address and mobile number without further consent for marketing, non-marketing or administrative purposes (such as notifying you of major changes, for customer service purposes, providing information about updates to “theweddingandevent" Services, billing, etc.). Any Information provided by you will not be considered as personal information if it is freely available and/or accessible in the public domain or is not deemed as personal information under the applicable law. Further, any reviews, comments, messages, blogs posted/uploaded/conveyed/communicated by Users on the public sections of the Site or an application store (like the App Store or Play Store) become published content and are not considered as personal information which is subject to this Policy. In case you choose to decline to submit Information on the “theweddingandevent" App/Site, we may not be able to provide certain services on the App/Site to you. We will make reasonable efforts to notify you of the same at the appropriate time. In any case, we will not be liable and or responsible for the denial of certain services to you for due to not receiving necessary Information from you. When you register with the “theweddingandevent" Services, we may (at our discretion) contact you from time to time about updating of your Information.</p>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Information automatically tracked while using the App or Site</h2>
          <p>Credit/Payment Records: We store all your credit/payment records in a cloud-based environment using the services of third-party infrastructure service providers, the data of which is not governed by this Privacy Policy. Customer Information: We store the contact information of your customers. We also keep a log of all the credit/payment-related communication to the customers. Demographic and Related Information: We may reference other sources of demographic and other information in order to provide you with more targeted communications and promotions. We use Google Analytics, among others, to track the User behavior on the Site. Log File Information: Our Servers automatically collect limited Information about your device's connection to the internet, including your IP address, when you visit our Site or use the App. We automatically receive and log Information from the App and/or your browser including but not limited to IP address, your device or computer's name, and your operating system, We may also collect log Information from your device, including but not limited to your location, IP address, your device's name, device's serial number or unique identification number (e.g. UDID on your iOS device, Android ID or ADID on your Android Device), your device operating system, browser type and version, CPU speed, and connection speed etc. Cookies: To improve the responsiveness of the Site for our Users, we may use "cookies", or similar electronic tools to collect information to assign each visitor a unique, random number as a User Identification (User ID) to understand the User's individual interests using the identified computer. By continuing to visit the App/Site, you are agreeing to the use of cookies and similar technologies for the purposes we describe in this Policy. If you prefer not to receive cookies or web beacons, then you should stop using Services, or consult your browsing and third-party cookie settings. We use cookies and other technologies for analysing and optimizing our websites as well as for marketing purposes. Our partners may also assign their own cookies to your browser, a process that we do not control.</p>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Link to third party sites/ad-servers</h2>
          <p>The Site may include links to other websites, such as advertisers, blogs, content sponsorships, vendor services, social networks, etc. Such websites are governed by their respective privacy policies, which are beyond our control. Once you leave our servers (you can tell where you are by checking the URL in the location bar on your browser), use of any information you provide is governed by the privacy policy of the operator of the site you are visiting and we make no representation or warranty on how your information is stored or used on third-party servers. That policy may differ from ours. If you can't find the privacy policy of any of these sites via a link from the website's homepage, you should contact the website directly for more information.</p>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Information sharing</h2>
          <p>The Information (including personal information) collected may be shared with our affiliates and group companies to the extent required for our internal business and/or administrative purposes and/or general corporate operations and to any third-party service providers, including marketing partners, and the User hereby consents to the same. We will take reasonable steps to ensure that these third-party service providers are obligated to protect your personal information and are also subject to appropriate confidentiality/non-disclosure obligations and they comply with the applicable provisions of the data protection laws. These entities, with whom we share the Information, may market to you as a result of such sharing unless you explicitly opt-out. The User explicitly consents that we may have access to your SMS, contacts in your directory, location and device information and we may request you to provide your CNIC and Know-Your-Customer (KYC) details to check your eligibility for certain products/services including but not limited to credit and payment products, identity documents etc., to enhance your experience and provide you access to the services being offered by us, our affiliates or other third-party service providers (including lenders). Further, the User also consents to sharing of Information (including sensitive personal information) when it is requested or required by law or by any court or governmental agency or authority to disclose, for the purpose of verification of identity, or for the prevention, detection, investigation including cyber incidents, or for prosecution and punishment of offences. These disclosures are made in good faith and belief that such disclosure is reasonably necessary for enforcing the Terms of Use or for complying with the applicable laws and regulations. No personal information of an individual User such as name, phone number, email address, spends data, card details etc. would be shared with any other User and/or third party unless explicitly approved by the concerned individual User himself/herself. We may also present information related to credit records, User spends, patterns and User data tracked by us only in the form of aggregated statistics on data such as overall app usage by date, time, balances, etc., within our App/Site or to our partners. By using the “theweddingandevent" Services and providing information to us, Users agree and consent to the disclosure, transfer, storage, and processing of the personal information (including the sensitive personal information) by us in Pakistan and / or in other countries to its affiliates, group companies and third parties. While our primary motive is to protect the disclosure of personal information (except in accordance with the provisions of this Policy) of Users, Users may note that countries where their Information may be stored, may not have data protection laws similar to the countries where they are located.</p>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Accessing and updating personal information</h2>
          <p>When Users use the Site (or any of its sub sites) / App, we make good faith efforts to provide Users, as and when requested by Users, with access to their Information and shall further ensure that any personal information or sensitive personal data or other Information found to be inaccurate or deficient shall be corrected or amended as feasible, subject to any requirement for such personal Information or sensitive personal data or Information to be retained by law or for legitimate business purposes. We ask individual Users to identify themselves and the Information requested to be accessed, corrected or removed before processing such requests, and we may decline to process requests that are unreasonably repetitive or systematic, require disproportionate technical effort, jeopardize the privacy of others, or would be extremely impractical (for instance, requests concerning Information residing on backup tapes), or for which access is not otherwise required. In any case, where we provide Information access and correction, we perform this service free of charge, except if doing so would require a disproportionate effort. Because of the way we maintain certain services, after you delete your Information, residual copies may take a period of time before they are deleted from our active servers and may remain in our backup systems.</p>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Information storage and backup</h2>
          <p>From time to time, we take backup of your data on “theweddingandevent" Online Platform on our cloud database. This is done for the purpose of enabling Users to get their data back in case their phone's data becomes unusable, or phone gets lost, or the User moves to a new phone device. We also use this backup to provide useful insights and information related to their spends such as weekly spends in a month, insights related to spend behavior, etc., and to provide information related to User spends, patterns and User data in the form of aggregated and anonymized statistics on data such as User spends by category, date, time, bank balances, etc. We shall keep User’s Information in our records till the period of time where we can potentially offer the “theweddingandevent" Services to the Users. After such period of time where “theweddingandevent" Services are no more relevant to a User, we remove all the Information pertaining to a particular User from our records, which may take time though.</p>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Information security</h2>
          <p>We take appropriate security measures to protect against unauthorized access to or alteration, disclosure or destruction of data including accidental or intentional manipulation, loss from access by unauthorized parties. These include internal reviews of our data collection, storage and processing practices and security measures, including appropriate encryption and physical security measures to guard against unauthorized access to systems where we store personal data. All Information gathered on the “theweddingandevent" Online Platform is securely stored within the controlled database. Access to the servers is password-protected and is strictly limited. Our security measures are regularly reviewed and updated to reflect technological developments. Regardless of where your personal information is transferred or stored, we take all steps reasonably necessary to ensure that personal information is kept secure, however, please understand that no transmission of data over the internet or any other public network can be guaranteed to be 100% (one hundred percent) secure. We seek to ensure compliance with the requirements of the applicable data protection laws to ensure the protection and preservation of the User’s privacy and personal Information. We have physical, electronic, and procedural safeguards that comply with the laws prevalent in specific jurisdiction to protect User’s Personal Information. By accepting the terms of this Policy, you agree that the standards and practices being implemented by us, are reasonable and sufficient for the protection of your personal information. We will contact you regarding any breach of the security, confidentiality, or integrity of your unencrypted electronically stored Personal Information to you via email or any other feasible manner in the most expedient time possible and without unreasonable delay, insofar as consistent with the legitimate needs of law enforcement and will undertake all measures necessary to determine the scope of the breach and restore the reasonable integrity of the data system.</p>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Purpose of Data Processing</h2>
          <p>We will only collect and process Personal Information about you where we have lawful basis to do so. Our primary purpose in collecting your information, including Personal Information from you is to deliver the personalized “theweddingandevent" Services and its various features. Please note that should you choose to not provide us consent to collect your information, including Personal Information, we may not be able to perform the contract with you. Where we refer to 'perform the contract' we mean the Terms of Use applicable to your use of the “theweddingandevent" Service or any independent contract we may have executed with you, which means that you may either not be able to access certain features of the “theweddingandevent" Service or we may not be able to provide you the “theweddingandevent" Service in entirety. For example, we use your information where we need the Personal Information to perform the contract with you (for example, to provide the Online Platform or our services to you) so as to:</p>
          <ul>
            <li>Register you on our Online Platform.</li>
            <li>Provide you with customer or technical support including addressing support queries related to, but not limited to, payment processing, or to diagnose any problems with our servers etc.</li>
            <li>Send you transactional emails/SMS or to provide you with information, direct marketing, online and offline advertising and other materials regarding products, services and other offers from time to time in connection with the “theweddingandevent"  Service or its parent, subsidiary and affiliated companies ("Platform Entities") and its joint ventures.</li>
            <li>Determine your geographic location, to provide you localized content including advertisements, personalized recommendations, allow you to continue watching/using previous content at another time, and to determine your Internet service provider to troubleshoot a technical issue, and help us quickly and efficiently respond to inquiries and requests;</li>
            <li>To provide you with a personalized service and experience; we do this by linking some or all of your Personal Information such as transactions done with “theweddingandevent" with your activity on our Online Platform across all your devices and associating and storing this information with a unique platform generated identifier that is generated for each user (guest as well as registered user). When a guest user subsequently registers and creates an account, the information and data relating to such user's past activities gets added to and associated to the registered account.</li>
            <li>Research, analyze and understand our audience and what content and advertising they may view, watch or otherwise engage with, in order to improve our service (including our user interface experiences and security features); evaluate your eligibility for certain types of offers, products or services and market such products or services to you; to perform analytics and conduct customer research, including general market research or surveying our customers' needs and opinions on specific issues, generating sales and traffic patterns, and to analyze advertising effectiveness, both on an anonymous basis (e.g., by aggregating data) or on an individual basis (if legally permissible), in combination with other information collected from tracking technologies and aggregate it with information collected from other Users using our Online Platform, to attempt to provide you with the Services and a better experience on the Online Platform. For example, one of the ways we use this information is to count the number of times an advert or other content is viewed because this might be the metric by which our advertisers pay us. This information is compiled and analyzed on an aggregated basis.</li>
            <li>Allow you to participate in interactive features such as Game play events on the Online Platform, providing you with relevant gameplay experience, determine and declaring winners and providing you with prizes.</li>
            <li>Analyze and measure how effective our advertising is by determining which media sources should be paid for delivering a desired action e.g. users who install our application or subscribe (also known as 'attribution'), so that we pay for demonstrated value and don't overspend.</li>
          </ul>
          <p>We will use your Personal Information with your explicit consent as follows:</p>
          <ul>
            <li>When you agree to share your precise location based on GPS data, we will combine this information with other information that you provide to us on the Platform to provide personalized content and advertisements with better accuracy basis your geographic location e.g. you may see more regional content recommendations or advertisements for local establishments, when you share your precise location based on GPS data;</li>
            <li>When you agree to share information pertaining to the applications frequently used by you on your device, we will combine this information with other information that you provide to us on the Online Platform, to display advertisements that are more relevant to your interest areas.</li>
            <li>Or otherwise, whenever the law requires us to get your permission or where we have stated we may seek your permission in this Privacy Notice. In some contexts, we use your Personal Information where we have a legal obligation to do so or to protect your vital interests or those of another person:</li>
            <li>Prevent, detect and investigate potentially prohibited or illegal activities, including fraud, and enforcing our terms (such as determining free trial eligibility);</li>
            <li>Confirming your identity if you are exercising legal rights;</li>
            <li>Notify you about changes in the Terms of Use or in this Privacy Notice;</li>
            <li>Carry out our obligations and enforce our rights arising from any contracts entered into between you and us/our distributor.</li>
            <li>When you access or use the Services or send any data, query, request or communication to us via our Support email, you understand that you are communicating with us electronically, and that we may respond via electronic means from us, such as by email.</li>
          </ul>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Revocation of consent</h2>
          <p>A User can revoke his consent to the processing of his personal information at any time with effect for the future. Please note that withdrawing consent does not affect our right to continue to collect, use and disclose personal information where such collection, use and disclose without consent is permitted or required under applicable laws.</p>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Responsible organization for the data collection</h2>
          <p>All the “theweddingandevent" Services are currently provided and regulated by MCT Business Private Limited and therefore MCT Business (Private) Limited is responsible for the collection, storage and processing of personal information of the Users, except where third party service providers have been hired by “theweddingandevent" to provide any service, in which case that third party entity shall be responsible.</p>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Updates/Changes</h2>
          <p>We may alter our Policy from time to time to incorporate necessary changes in technology, applicable law or any other variant. In any case, we reserve the right to change (at any point of time) the terms of this Policy or the Terms of Use. Any changes we make will be effective immediately on notice, which we may give by posting the new policy on the Site. Your use of the “theweddingandevent" Services after such notice will be deemed acceptance of such changes. We may also make reasonable efforts to inform you via electronic mail. In any case, you are advised to review this Policy periodically on the Site to ensure that you are aware of the latest version.</p>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Questions/Grievance Redressal</h2>
          <p>In the event you have any grievance relating to the processing of Information provided by you, you may contact our relationship Manager at (*) or write to us at the following email address: info@theweddingandevent.com</p>
          <h2 className="mt-10 mb-4 text-2xl font-bold text-[#d13f43]">Disclaimer</h2>
          <p>In case any personal information is shared by you with us, which is not requested by us during registration, whether mandatorily or optionally, we will not be liable for any information security breach or disclosure in relation to such information. If you have any questions regarding this Policy or the protection of your personal information, please contact our data protection Manager/ Relationship Manager.</p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
